package cli

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

// newGenCommand provides hidden generators. `oiax gen docs` writes the
// command reference consumed by the verify-generated CI gate; the
// reference is generated from the command tree, never hand-written.
func newGenCommand() *cobra.Command {
	gen := &cobra.Command{
		Use:    "gen",
		Short:  "Generate development artifacts",
		Hidden: true,
	}

	var outPath string
	docs := &cobra.Command{
		Use:   "docs",
		Short: "Generate the CLI command reference",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return writeCommandReference(cmd.Root(), outPath)
		},
	}
	docs.Flags().StringVar(&outPath, "out", filepath.Join("docs", "reference", "cli.md"), "output file")

	gen.AddCommand(docs)
	return gen
}

// writeCommandReference renders the whole visible command tree into one
// Markdown file, deterministically (no timestamps).
func writeCommandReference(root *cobra.Command, outPath string) error {
	var buf bytes.Buffer
	buf.WriteString("# CLI reference\n\n")
	buf.WriteString("<!-- Generated by `oiax gen docs`. Do not edit by hand; CI gates on drift. -->\n\n")

	var render func(cmd *cobra.Command) error
	render = func(cmd *cobra.Command) error {
		if err := doc.GenMarkdown(cmd, &buf); err != nil {
			return err
		}
		for _, sub := range cmd.Commands() {
			if !sub.IsAvailableCommand() || sub.IsAdditionalHelpTopicCommand() {
				continue
			}
			if err := render(sub); err != nil {
				return err
			}
		}
		return nil
	}
	if err := render(root); err != nil {
		return fmt.Errorf("render command reference: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outPath, buf.Bytes(), 0o644)
}
